# .github/workflows/fetch-blogdata.yml
name: Fetch Blog Data from Strapi

on:
  schedule:
    - cron: '0 * * * *' # Every hour
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch-blogdata:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Disable postinstall
        run: |
          node -e "let p=require('./package.json');p.scripts=p.scripts||{};p.scripts.postinstall='true';require('fs').writeFileSync('package.json',JSON.stringify(p,null,2));"

      - name: Fetch blog posts from Strapi and update blogdata.json
        env:
          STRAPI_API_URL: ${{ secrets.STRAPI_API_URL }}
        run: node scripts/fetchBlogData.js

      - name: Commit and push blogdata.json
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: update blogdata.json from Strapi [skip ci]'
          file_pattern: public/blogdata.json

      - name: Install sitemap package
        run: npm install sitemap

      - name: Generate sitemap.xml
        run: node scripts/generateSitemap.js

      - name: Commit and push sitemap.xml
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: update sitemap.xml [skip ci]'
          file_pattern: public/sitemap.xml

      - name: Trigger site deployment
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: trigger-deploy
